### ISSUE TITLE
Rogue

### ISSUE THREAD

**Issue by Crpeekaboo** [Vae2009/ConROC#10]
On Rogue getting these 5 error messages.
Seems to be a high number of error counts.
Sorry for all the characters being reported on.
I am sure it's something that's a simple fix.
Wish I could help more.
Please see screenshot.
![20241226_144925](https://github.com/user-attachments/assets/9f7f5b2b-247b-4527-bdf3-1d2ce14e06a5)
![20241226_144938](https://github.com/user-attachments/assets/1a891dbf-f107-4d6e-8f59-39b5d0e1c096)
![20241226_144951](https://github.com/user-attachments/assets/81b9fd8e-b1fa-4321-806c-25305b2cda42)
![20241226_145004](https://github.com/user-attachments/assets/26f57690-48f6-4d41-a09f-ad183a584a09)
![20241226_145031](https://github.com/user-attachments/assets/f6faab80-e9f2-4e42-9d2d-344033887bf6)

**Comment by Crpeekaboo** [comment]
Here's two attachments with zero addon's and a complete reload of WOW.

I am have to disable ConRo as it won't stop giving errors... 
This is very puzzling.
 
[Page #1.docx](https://github.com/user-attachments/files/18256546/Page.1.docx)
[Page #2.docx](https://github.com/user-attachments/files/18256547/Page.2.docx)

Thanks

**Comment by Crpeekaboo** [comment]
Update on Rogue after update.
These are the 4 error messages that pop up a lot. If you land, go to stealth or perform an action, these will pop up.
Also shows no spell to use or cast.

**Page #1 When landing or going into stealth error**
 
Message: Interface/AddOns/ConROC_Rogue/rogue.lua:174: attempt to index field 'optionMaxIds' (a nil value)
Time: Fri Dec 27 11:16:05 2024
Count: 8
Stack: Interface/AddOns/ConROC_Rogue/rogue.lua:174: attempt to index field 'optionMaxIds' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ConROC_Rogue/rogue.lua"]:174: in function `NextSpell'
[string "@Interface/AddOns/ConROC/core.lua"]:1105: in function `?'
[string "@Interface/AddOns/ConROC/Libs/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...ddOns/ConROC/Libs/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:

**Page # 2 Rogue error message**

Message: Interface/AddOns/ConROC_Rogue/rogue.lua:174: attempt to index field 'optionMaxIds' (a nil value)
Time: Fri Dec 27 11:26:54 2024
Count: 5
Stack: Interface/AddOns/ConROC_Rogue/rogue.lua:174: attempt to index field 'optionMaxIds' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ConROC_Rogue/rogue.lua"]:174: in function `NextSpell'
[string "@Interface/AddOns/ConROC/core.lua"]:1105: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConROC/buttons.lua"]:1880: in function `?'
[string "@Interface/AddOns/ConROC/Libs/Ace3/AceTimer-3.0/AceTimer-3.0.lua"]:55: in function <...ddOns/ConROC/Libs/Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:

**Page # 3 Rogue error message**

Message: Interface/AddOns/ConROC_Rogue/rogue.lua:174: attempt to index field 'optionMaxIds' (a nil value)
Time: Fri Dec 27 11:31:12 2024
Count: 1
Stack: Interface/AddOns/ConROC_Rogue/rogue.lua:174: attempt to index field 'optionMaxIds' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ConROC_Rogue/rogue.lua"]:174: in function `NextSpell'
[string "@Interface/AddOns/ConROC/core.lua"]:1105: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConROC/core.lua"]:1035: in function `?'
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ConROC/Libs/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ddOns/ConROC/Libs/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:

**Page #4 Rogue**

Message: Interface/AddOns/ConROC_Rogue/rogue.lua:174: attempt to index field 'optionMaxIds' (a nil value)
Time: Fri Dec 27 11:33:08 2024
Count: 1
Stack: Interface/AddOns/ConROC_Rogue/rogue.lua:174: attempt to index field 'optionMaxIds' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ConROC_Rogue/rogue.lua"]:174: in function `NextSpell'
[string "@Interface/AddOns/ConROC/core.lua"]:1105: in function `InvokeNextSpell'
[string "@Interface/AddOns/ConROC/core.lua"]:1035: in function `?'
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ConROC/Libs/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ddOns/ConROC/Libs/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:

**Comment by Crpeekaboo** [comment]
Played Rogue some yesterday and today.
Tried many things and still same errors as above.
When flying out to another place and land errors pop up. When selecting stealth erros pop up. Seems on any function.

**Comment by Crpeekaboo** [comment]
Good morning
After new update Rogue freezes up the screen badly. There were 14 or 15 pages that I couldn't look through to copy the issues. You could here the audio, but the freezes were so bad it disconnected.

**Comment by Crpeekaboo** [comment]
I tried the Rogue once more and tied to capture all I could. It took a while before major screen lock up.
Here's 20 screenshot is all I could get.. clicking to go to next page my pointer would spin.
![20241231_090515](https://github.com/user-attachments/assets/8c900832-383c-41f1-a502-36ec57832095)
![20241231_090629](https://github.com/user-attachments/assets/97f08710-60a2-4c16-9785-36eeb478a5a1)
![20241231_092233](https://github.com/user-attachments/assets/29d0a119-1a40-47e1-ad61-32d38411ff5b)
![20241231_092039](https://github.com/user-attachments/assets/bb103483-bdeb-40f3-9aa8-66a786d17001)
![20241231_091959](https://github.com/user-attachments/assets/f07d5068-81fc-469c-84d6-64e8f2fdab41)
![20241231_091605](https://github.com/user-attachments/assets/ca3c113b-694f-402d-9390-09e0b999c98a)
![20241231_091523](https://github.com/user-attachments/assets/f96515d7-4005-4d5a-82ed-b470ad54e1e5)
![20241231_091447](https://github.com/user-attachments/assets/81a8cad3-3cf6-4523-bfa6-4e46f811aa98)
![20241231_091408](https://github.com/user-attachments/assets/8bbf3bb3-12a0-4295-a061-43f0c546f08d)
![20241231_091331](https://github.com/user-attachments/assets/ac9125f0-ceef-44e0-a9e7-d2f84549007b)
![20241231_091247](https://github.com/user-attachments/assets/eb052754-a67b-4bdb-b283-8e3a4f05b029)
![20241231_091210](https://github.com/user-attachments/assets/cba860ca-1467-4ec9-aef8-f4cb3ff7e90f)
![20241231_091145](https://github.com/user-attachments/assets/0436b953-73e9-4cd5-82aa-0c4e795578c8)
![20241231_091057](https://github.com/user-attachments/assets/e760ff6b-41e6-4b57-9e69-1fa9c27746db)
![20241231_091023](https://github.com/user-attachments/assets/88a650a6-c550-49ae-898d-87af15e5ca0c)
![20241231_090954](https://github.com/user-attachments/assets/7dfe8a62-ded9-4732-a580-cfd5f2540376)
![20241231_090858](https://github.com/user-attachments/assets/1fb4afff-8f6b-44b8-9063-b0882330065c)
![20241231_090823](https://github.com/user-attachments/assets/f230ddb0-0691-4e8a-ab37-1c0ecaa7e598)
![20241231_090741](https://github.com/user-attachments/assets/44c4f4cd-2bdc-421e-8dad-a4a6a50f7c03)
![20241231_090704](https://github.com/user-attachments/assets/d1c6c715-af2c-4d00-901b-49655e7ecfbc)

**Comment by Vae2009** [comment]
Thank you for this, it made finding an error very easy. Hopefully the only issue, fixed in Rogue v1.15.16
