### ISSUE TITLE
Issues after the update

### ISSUE THREAD

**Issue by Crpeekaboo** [Vae2009/ConROC#4]
Hello,
This has been my favorite addon to date.
I am getting many errors on my Pally almost on every hit I do on a creature. A screen pops up to asking to reload.
I had this happen on the Rogue as well. Haven't tried on the other characters. This seem to start after the updates.

Just checked on Rogue and both Rigue and Pally had to turnoff the add on. Eveytime there would be an error... Will check other characters later.

Thanks

**Comment by Vae2009** [comment]
Rogue I am working on doing the update for today. Pally has been updated though. Can you give me the verions you have for the Base addon and Pally... and then if possible the addon Bug Grabber can give you the error code for me to see why Pally maybe breaking.

**Comment by Crpeekaboo** [comment]
Will do... I am at work and will be heading home here shortly...

Were can I donate?

Thanks

**Comment by Vae2009** [comment]
No rush, I to am at work right now. 

I appreciate the support.
https://paypal.me/Vae2009 or https://www.patreon.com/vae2009

**Comment by Crpeekaboo** [comment]
Here's 3 screenshot for Pally.

Hope youbcan see it.
Version 1.15.5

**Comment by Vae2009** [comment]
No images or links are shown

**Comment by Vae2009** [comment]
It maybe because, you are responding through the email?

**Comment by Crpeekaboo** [comment]
Sorry, I did respond through email with images.
Let me try something else.

**Comment by Crpeekaboo** [comment]
![20241213_170059](https://github.com/user-attachments/assets/bb265eb8-89cd-470d-9267-1a0960f0a319)

**Comment by Crpeekaboo** [comment]
![20241213_170110](https://github.com/user-attachments/assets/0e166780-0a57-4acb-8097-3485bdcbfa69)

**Comment by Crpeekaboo** [comment]
![20241213_170117](https://github.com/user-attachments/assets/946e1bfc-2548-469a-95b7-e8d83324effc)

**Comment by Vae2009** [comment]
Got it, easy miss and easy fix

**Comment by Vae2009** [comment]
look for Pally update v1.15.12

**Comment by Crpeekaboo** [comment]
Wow you're quick!!!
Tomorrow I will be donating :)
I am currently at the movies.

Thank you!!!

**Comment by Crpeekaboo** [comment]
Good morning,
I found more erro on Warrior I like to share.
![20241218_060323](https://github.com/user-attachments/assets/e9ed33b3-7905-414d-a264-ac59c20b4075)

**Comment by Crpeekaboo** [comment]
#2
![20241218_060334](https://github.com/user-attachments/assets/a10b01e2-0632-4f52-b6ee-22362aa662a0)

**Comment by Crpeekaboo** [comment]
#3
![20241218_060343](https://github.com/user-attachments/assets/f82dcc49-19d7-4ba7-b34a-f099be174bd2)

**Comment by Crpeekaboo** [comment]
#4
![20241218_060351](https://github.com/user-attachments/assets/d9a38c6f-6790-4e4a-a31b-df81b0d420df)

**Comment by Crpeekaboo** [comment]
![20241218_062141](https://github.com/user-attachments/assets/e70c696e-1208-4890-9808-19670a28dead)

**Comment by Crpeekaboo** [comment]
![20241218_062131](https://github.com/user-attachments/assets/eb5d9a3a-1a91-4fbd-8537-96a1ada3a64c)

**Comment by Crpeekaboo** [comment]
![20241218_062107](https://github.com/user-attachments/assets/7f71ab84-c675-4d28-8c46-8171c9932e17)

**Comment by Crpeekaboo** [comment]
![20241218_062053](https://github.com/user-attachments/assets/2b69376e-ceb0-4945-9be1-4c6138eb037f)

**Comment by Vae2009** [comment]
Thank you for the report. i will comb through these as soon as I can.

**Comment by Vae2009** [comment]
Let's see if this Fixes it for warrior

**Comment by Crpeekaboo** [comment]
Hello,
This is what's happening when logging onto the Warrior.
![20241219_062440](https://github.com/user-attachments/assets/e414ff73-36d4-4dd4-9864-5c58712638ea)
![20241219_062454](https://github.com/user-attachments/assets/6bd6043c-165d-4dd5-bd78-0676b00604cb)

**Comment by Crpeekaboo** [comment]
This is what's happening when Targeting.
![20241219_062743](https://github.com/user-attachments/assets/210af566-2bd9-4183-9baf-876526940e3c)
![20241219_062756](https://github.com/user-attachments/assets/7727f048-f2aa-4fa5-bf75-758f3c948fb0)

**Comment by Crpeekaboo** [comment]
Seems to start when in Defence Stance
![20241219_063244](https://github.com/user-attachments/assets/0cfbca2e-93dd-4945-b689-9e198c8025f3)

**Comment by Crpeekaboo** [comment]
Last thing I see is this.
I have moved around serveral.location and it still say not fou d on action bar.
![20241219_063526](https://github.com/user-attachments/assets/090e8384-fa7d-4baf-be9b-1149aab36622)

**Comment by Crpeekaboo** [comment]
All Characters do this when logging on.
I didnupdatebto new version. I am heading into work and will reach back if I find anything else.
![20241219_064023](https://github.com/user-attachments/assets/0b6b326a-4bd6-43c7-b450-355a67b6c4ae)

**Comment by Vae2009** [comment]
Warrior v1.15.14 Hopefully will fix some of these. Working on fixes for the rest.

**Comment by Crpeekaboo** [comment]
Good morning,
Giving you feedback on Warrior.
The attached showing that it doesn't recognize Thunder Clap. The other issue is it doesn't show next rotations. Meaning not what the next spell will be. I did delete everything and reinstalled with same issue. I checked to be sure the latest spell is in the action bar. I even placed in different locations. I hope you don't mind the feedback and 100% appreciate what your doing for this addon. I will test others characters and provide feed back as well... so many people like the addon and I am trying to get many others to use it and give support through donations.

![Thunder Clap Warrior](https://github.com/user-attachments/assets/a0ca8136-b4bd-491c-95f0-df5a5d433e21)

**Comment by Crpeekaboo** [comment]
Hello,
Here's another feedback on Rogue. There's 5 errors that pop up that I can tell and I will attach those. I also will attach the spell book that shows none selected. When selecting in the spell book it will revert back to none. Seems not to recognize unless I am missing something. I did reload several times but some issue. Also on action bar it doesn't give next selection.

![Rogue](https://github.com/user-attachments/assets/51c19594-49fd-469d-873f-3557ae7482ea)
![Rogue 1](https://github.com/user-attachments/assets/c1953d20-2485-4038-bc52-7502869d1c70)
![Rogue 3](https://github.com/user-attachments/assets/d0a17e7a-2853-4c06-8bb8-414a13c08d08)
![Rogue 4](https://github.com/user-attachments/assets/3b6ebedb-ce38-4b4a-85e7-80e8a2bc3fa8)
![Rogue 2](https://github.com/user-attachments/assets/adba6bfe-ca4c-46d6-9e1f-821d5ac8bf60)
![Rogue 5](https://github.com/user-attachments/assets/67f12577-3613-48c1-ae59-4084d8924a93)

**Comment by Crpeekaboo** [comment]
Pally seems for the most part work, but when selecting in the spell book from melee to pvp it will stop showing next spell to select on action bar. Seems to be mostly related to spell book section. Example selecting a different buff not recognizing. The other thing is when signing on and I believe it is with all characters I get this error to reload.
I don't want to over load you at all and will test the Warlock, Hunter and Mage later and if I find anything post them later on.
![Pally](https://github.com/user-attachments/assets/b0c3619e-9c8b-461b-a45f-aba2a15cd311)

**Comment by Crpeekaboo** [comment]
Warlock update from testing.
I get an error saying Drain Life isn't on the action bar. I moved drain life in several locations and say message. Could it be due to Master Channler rune in the attachment? I also don't get it wanting to recognize Curse of Agony. Everything else seems to work correctly except the first time logging on I get the same error as the Pally above.

![Warlock 1](https://github.com/user-attachments/assets/0ff97912-b7a8-4e0b-bfb0-6e5e9a63771f)
![Warlock 2](https://github.com/user-attachments/assets/885b1957-2876-4ba5-9ed1-136c065e0c0b)
![Warlock 3](https://github.com/user-attachments/assets/c35ddbf6-ba1c-41cb-8934-3b7ecfbc1f20)
![Warlock 4](https://github.com/user-attachments/assets/73756c31-7776-4699-bf88-312ca5586623)

**Comment by Crpeekaboo** [comment]
Hunter update:
The pictures are of the hunter are shown. This happened twice, not sure the answer. I do know when selecting abilities for Hunter mark, Chimera and Aimed Shot it would on recognize Hunter Mark. Not sure if that's by design. Sorry for all these messages, just giving feedback. I wish I knew how to correct these I would help :). This will be all for today as I know you may have lots going on. Those 6 characters are the only ones I play. I am trying to get others to try your addon out and donate :) 
![Hunter](https://github.com/user-attachments/assets/07454b39-0621-45dd-aef5-643ecacae105)
![Hunter 1](https://github.com/user-attachments/assets/3f1da1b0-3389-4b76-9c45-1dae25ea9fac)
![Hunter 2](https://github.com/user-attachments/assets/db169a0e-c56d-4f25-8ff6-1049cafecadb)
![Hunter 3](https://github.com/user-attachments/assets/edb9036e-7bc9-4d00-a2d2-ef6166c8eebb)
![Hunter 4](https://github.com/user-attachments/assets/bb231627-8633-444c-9221-f39c0f3b6f10)
![Hunter 5](https://github.com/user-attachments/assets/3a63cf0d-6bd6-4fbb-ad20-1f0360229b39)
![Hunter 6](https://github.com/user-attachments/assets/534e8b1a-eb41-4b12-9c4b-477b229f33e0)

Thanks

**Comment by Crpeekaboo** [comment]
Sorry for all the updates and attachments.
Still same issues as above. I have disabled all other add-ons including removing them just incase there were conflict issues and still getting the above errors...

Thanks

**Comment by Vae2009** [comment]
Okay, I put out a update to all classes for the spellmenu not saving issue. I am not sure if that covers any of these issues. But we should start seperating each problem out into seperate tickets and maybe within the class repo they belong too, please.
