### ISSUE TITLE
[Bug] Class Window not refreshing after combat

### ISSUE THREAD

**Issue by Starlynk1** [Vae2009/ConROC#5]
After combat ends, the class window doesn't appear to be refreshing to show the available options. Reload refreshes the spellmenu and then it loads correctly until combat. Appears it needs a refresh after combat.

**Comment by Vae2009** [comment]
That's odd, I have been playing with the window open most the time and combat doesn't trigger anything.

The issue I am still trying to figure out is when you learn a new rank of a spell, you have to reload for the spellmenu to update.

**Comment by Vae2009** [comment]
Can you give me , class, lvl and server type. This is happening? ie. Sod or Anniv

**Comment by Starlynk1** [comment]
then not sure what is causing it. I seem to see it happen after combat and I open the window. Reload makes it work again. Any ideas on some steps you want me to try to narrow it down?

**Comment by Starlynk1** [comment]
HC Anniv, Hunter 20
But its happened on other classes as well, so don't think its solely related to class.

**Comment by Starlynk1** [comment]
I've been keeping the window open to try and catch when it happens. So far it's behaving as it should. I will continue to monitor it to see when it happens. So far, doesn't look to be combat related for now.

**Comment by Vae2009** [comment]
Check when you learn new spell rank

**Comment by Starlynk1** [comment]
I kept it open when I learned new spells, not rank up spells though. All that happened is the window closed to refresh. Then I opened with it normal still. I will watch for my first rank up spell to see what happens.

**Comment by Starlynk1** [comment]
Just had an update to a rank spell and the window is now blank besides the Spec options. Reload fixes the window.

**Comment by Vae2009** [comment]
Let's see if this new version helps at all.

**Comment by Starlynk1** [comment]
Just had a spell rank up and so far so good. I will continue watching, but seems like this can be closed. I will open another issue ticket if something happens.

Thank you!
