### ISSUE TITLE
Warlock

### ISSUE THREAD

**Issue by Crpeekaboo** [Vae2009/ConROC#8]
Seems all updates are working. 
The only thing I see on the Warlock is that when using the Rune Master Channeler that says your drain life is no longer channeled. I get an error that drain life isn't found on action bar.
The other error I get is that when having Haunt on the first action bar it tells me it's not found on the action bar, but if I if move it to a different action bar it works (like swapping the wand to be the 1st action bar and haunt the 2nd it works). All other updates really made a big difference in rotations :)
![20241226_085402](https://github.com/user-attachments/assets/4ae325e4-ea95-4fdb-9386-7cc9ee6d7459)
![20241226_085412](https://github.com/user-attachments/assets/45f57127-c66f-4af3-aeb7-5fd734b5c23e)
![20241226_085609](https://github.com/user-attachments/assets/5e71d796-b13a-49a4-8e71-66841db37dc2)
![20241226_085625](https://github.com/user-attachments/assets/fd9fe29e-a183-40d8-9661-54fef233990c)

**Comment by Crpeekaboo** [comment]
Quick comment... The not found on action bar did come up even not on first key #1 on action bar.. it seem to do this and than not show it again for a while.. not sure the issue.

**Comment by Vae2009** [comment]
It maybe your action bar addon, they tend to use different names for the bar

**Comment by Vae2009** [comment]
SOI found the FCF_Dockupdate error, I think you mentioned. I just am not sure why ConROC is causing it as the error doesn't show any ConROC code. This is a mystery one.

**Comment by Crpeekaboo** [comment]
Other than that error everything seems to work fine. It's only on that one spell. All.others work correctly. 
I am resting Pally and did find the same error... It be a separate ticket. It show more of a message error.
Thank you for your hard work on this.

**Comment by Crpeekaboo** [comment]
Happy to report that the last update seem to fix the issues... everything seemed to be working with no errors.

Great Job!!!

**Comment by Vae2009** [comment]
Awesome
